In [3]:
import numpy
import numpy as np

In [5]:
a = numpy.array([10, 20, 30, 40])


array([10, 20, 30, 40])

In [6]:
type(a)

numpy.ndarray

In [7]:
mat = numpy.array([[1, 2], [3, 4]])
mat

array([[1, 2],
       [3, 4]])

In [9]:
print(mat[1][1])
print(mat[-1][-1])

4
4


In [10]:
mat[1,:]

array([3, 4])

In [12]:
mat[:,0]

array([1, 3])

In [13]:
mat.transpose()

array([[1, 3],
       [2, 4]])

In [16]:
m1 = numpy.array([[1, 2], [3, 4]])
m2 = numpy.array([[5, 6], [7, 8]])
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [ ]:
m3 = numpy.array([1,2,3,4])
mp.sum()

In [19]:
b = np.array([[2, 4], [6, 8]])
print(b.mean())
print(b.diagonal())
print(a.ndim)

5.0
[2 8]
1


In [21]:
list = [1, 2, 3, 'nome']
list

[1, 2, 3, 'nome']